In [1]:
import numpy as np                                     

In [6]:
a = np.array([1,2,3])
print(a)
print(a.shape)
b = np.array([
    [1,2,3],
     [4,5,6]
     ])
print(b)
print(b.shape)

[1 2 3]
(3,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [14]:
c = np.arange(1,10,.2) 
print(c)
print(c.shape)
d = np.linspace(1,10,20)
print(d)

[1.  1.2 1.4 1.6 1.8 2.  2.2 2.4 2.6 2.8 3.  3.2 3.4 3.6 3.8 4.  4.2 4.4
 4.6 4.8 5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7.  7.2 7.4 7.6 7.8 8.
 8.2 8.4 8.6 8.8 9.  9.2 9.4 9.6 9.8]
(45,)
[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [16]:
print(c.ndim)

1


In [20]:
print(c.reshape(3,3,5))

[[[1.  1.2 1.4 1.6 1.8]
  [2.  2.2 2.4 2.6 2.8]
  [3.  3.2 3.4 3.6 3.8]]

 [[4.  4.2 4.4 4.6 4.8]
  [5.  5.2 5.4 5.6 5.8]
  [6.  6.2 6.4 6.6 6.8]]

 [[7.  7.2 7.4 7.6 7.8]
  [8.  8.2 8.4 8.6 8.8]
  [9.  9.2 9.4 9.6 9.8]]]


In [23]:
np.random.randint(-99,99,(3,5,3))#tupple used to be passed in round brackets

array([[[-64,  38,  83],
        [-45,  -7, -17],
        [  0,   6, -80],
        [-90,  75, -97],
        [-57, -76, -75]],

       [[ 76, -87, -70],
        [ 58,   0, -79],
        [-10, -29, -29],
        [ 49, -38,  86],
        [-44, -74, -61]],

       [[ 63, -50, -92],
        [-31, -91, -97],
        [ 86, -66,   5],
        [ 33, -69,  25],
        [ 76, -56,   6]]])

In [24]:
#maths in numpy
x = np.array([
    [2,3,4],
    [4,5,6]
])
y = np.array([
    [2,3,5],
    [4,6,6]
])


In [25]:
print(x+y)

[[ 4  6  9]
 [ 8 11 12]]


In [26]:
print(x-y)

[[ 0  0 -1]
 [ 0 -1  0]]


In [27]:
print(x*y)

[[ 4  9 20]
 [16 30 36]]


In [28]:
print(x/y)

[[1.         1.         0.8       ]
 [1.         0.83333333 1.        ]]


In [29]:
print(x ** y)

[[    4    27  1024]
 [  256 15625 46656]]


In [30]:
print(x % y)

[[0 0 4]
 [0 5 0]]


In [32]:
print(x*3)
print(x % 2)

[[ 6  9 12]
 [12 15 18]]
[[0 1 0]
 [0 1 0]]


In [33]:
print(x.dot(y))

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [34]:
y.T

array([[2, 4],
       [3, 6],
       [5, 6]])

In [38]:
print(x.dot(y.T))
print(np.matmul(x,y.T))
print(x @ y.T)

[[33 50]
 [53 82]]
[[33 50]
 [53 82]]
[[33 50]
 [53 82]]


In [40]:
#statistical functions
print(x.sum()) # sum of all elements
print(x.sum(axis=0))# sum of columns
print(x.sum(axis=1))# sum of rows
print(x.mean())# mean of all elements
print(x.std())# standard deviation of all elements
print(x.max())# maximum of all elements
print(x.min())# minimum of all elemnts
print(x.argmax())#index of maximum elements
print(x.argmin())#index of minimum elements

24
[ 6  8 10]
[ 9 15]
4.0
1.2909944487358056
6
2
5
0


In [41]:
# trignometric functions
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))#inverse sin

[[ 0.90929743  0.14112001 -0.7568025 ]
 [-0.7568025  -0.95892427 -0.2794155 ]]
[[-0.41614684 -0.9899925  -0.65364362]
 [-0.65364362  0.28366219  0.96017029]]
[[-2.18503986 -0.14254654  1.15782128]
 [ 1.15782128 -3.38051501 -0.29100619]]
[[nan nan nan]
 [nan nan nan]]


C:\Users\Lenovo\AppData\Local\Temp\ipykernel_15612\637509084.py:5: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))


In [42]:
#indexing
print(x[0,0])
print(x[0,:])
print(x[:,0])
print(x[:2,:2])
print(x[:2])



2
[2 3 4]
[2 4]
[[2 3]
 [4 5]]
[[2 3 4]
 [4 5 6]]
